### ISSUE TITLE
Modifying the filter on the server

### ISSUE THREAD

**Issue by roly445** [TrevorPilley/Net.Http.WebApi.OData#103]
Hi,  I have a scenario where I want to add additional parameters to the filter that is passed up to the server.  I'm not sure if it is possible, but any help would be appreciated.

Thanks

**Comment by TrevorPilley** [comment]
The `$filter` representation is immutable so you can't modify the `ODataQueryOptions.Filter.Expression` object, however you could modify the incoming URL before `ODataQueryOptionsHttpParameterBinding` reads the URL to build the `ODataQueryOptions` object.

Your other option is to apply any additional constraints after parsing the `ODataQueryOptions.Filter.Expression`.

If you can provide an example of what you are thinking of doing and how you use the `ODataQueryOptions.Filter.Expression` currently, I may be able to offer some other ideas?

**Comment by roly445** [comment]
So what we kind of have is a multi tenant system running from one database. What I was hoping to do was to inject the 'ClientId', and maybe even a 'ClientLocationId' into every single request.  This information is stored on the server and never passed down to the client.

**Comment by TrevorPilley** [comment]
OK, have you written your own code to parse the `ODataQueryOptions.Filter.Expression`?

**Comment by roly445** [comment]
Not yet, I will try and take a look at that later on this evening. I'll keep you posted.

**Comment by TrevorPilley** [comment]
What's parsing it at the moment?

**Comment by TrevorPilley** [comment]
@roly445 do you still need this open?

**Comment by roly445** [comment]
No, sorry I'll close it off. Thanks.
