### ISSUE TITLE
Add Support for grouping

### ISSUE THREAD

**Issue by roly445** [TrevorPilley/Net.Http.WebApi.OData#36]
At the moment  (propa eq 'r' and propb eq 'p') or propc eq 'g' breaks the provider.  Is it at all possible if you could have a look at adding grouping?

Thanks

**Comment by TrevorPilley** [comment]
I can have a look, how do you think it should be represented in the object model?

**Comment by roly445** [comment]
I'm not sure, what do you mean exactly?

**Comment by TrevorPilley** [comment]
Is it just a parsing issue where it doesn't cater for the `(` and `)`? or does the `ODataQueryOptions` class (or one of its properties) need some special support?

Feel free to send me a failing test and I'll have a look

**Comment by roly445** [comment]
I think it's just a parsing issue but the expressions would have to be
placed in some form of nested tree to generate the correct SQL.

**Comment by TrevorPilley** [comment]
It's a 2 step process, the OData query string is parsed by this library into an object graph - the translation from that graph to SQL is down to the consumer.

**Comment by roly445** [comment]
So do you think it's possible?

**Comment by TrevorPilley** [comment]
If it's just that my parsing logic doesn't cater for parenthesis then it can be fixed - what happens when you try it? do you get an exception (post the stack trace if you do)? Are you using this library yourself and generating SQL or are you using it as part of MicroLite.Extensions.WebApi?

**Comment by roly445** [comment]
There is no exception just a message saying it's unsupported.

I'm not using it with the web api directly,  I'm creating the
odataqueryoptions from a string as the odata query is part of a post body.

**Comment by TrevorPilley** [comment]
OK, can you post the actual method so I can see what's going on?

**Comment by roly445** [comment]
Ok in this case the *filterRawValue* is:
```
?$filter=(((FirstName eq 'andrew') and (LastName eq 'davis')) or (FirstName eq 'system'))&
```

```c#
var r = new HttpRequestMessage(Request.Method, Request.RequestUri + filterRawValue);
var queryOptions = new ODataQueryOptions(r);
var results = await this._session.PagedAsync<T>(queryOptions.CreateSqlQuery<T>(), queryOptions.GetPagingOptions());
```
The code generates this error: 
```
The expression '(FirstName eq 'system'))' is not currently supported.
```

I hope this helps.

**Comment by TrevorPilley** [comment]
That should give me enough to go on, just out of curiosity though why are you manually creating the HttpRequestMessage and ODataQueryOptions?

**Comment by roly445** [comment]
Security really, the whole API will be place under SSL and auth'd but I didn't want any chance that the URLs could be spoofed.  So to help with that all the 'GET' requests are actually posts with the odata query in the request body.

**Comment by TrevorPilley** [comment]
That seems a little unnecessary, the URL will be encrypted by the SSL connection

**Comment by roly445** [comment]
How do you figure that? Performing a get request to a https url is the same url as a http one.

**Comment by TrevorPilley** [comment]
It's not, the SSL connection is established before any data is transmitted and all data is then encrypted during transport, the only places the URL data would be unencrypted is on the machine that sends it and the machine which terminates the SSL connection - see this for further info http://stackoverflow.com/questions/2629222/are-querystring-parameters-secure-in-https-http-ssl

**Comment by roly445** [comment]
Oh, I have been doing this for 8 years and I did not know that

**Comment by TrevorPilley** [comment]
I only fully understood it recently, I'd assumed incorrectly that the URL was always readable! Should make your implementation easier now you know though!

**Comment by TrevorPilley** [comment]
I've had a bit of a look into the original issue by the way, the code I wrote originally to parse the URL into the ODataQueryOptions object is fairly naive and has been made more complex over time as I've added support for additional parts of the OData spec so this would be a good opportunity for me to rewrite that portion whilst adding the parenthesis support.

As a short term thing so you're not held up waiting for me to update this and since you're using MicroLite too, you might be able to play about with the order of the and/or predicates in the $filter and inspect the resulting SqlQuery to see if it generates the correct SQL. I think if you put the or at the end without parenthesis it might do what you expect anyway as the SQL generation wraps each predicate in parenthesis itself

**Comment by roly445** [comment]
Ok I'm currently using some other code to convert a linq statement info the
odata statement so in the short term I can have a look at removing the
brackets from it for simple queries and possibly create temporary endpoints
for the more complex ones.

I'm really liking the speed that microlite has given to my reads and with
the async methods in the new library it's even better, and I'm even
planning on writing some tutorials on my blog about what I have done with
it if you want to link them to your site at some point.

**Comment by TrevorPilley** [comment]
Yeah, that would be great!

**Comment by TrevorPilley** [comment]
OK, I'm going to do this in 2 stages, stage 1 will be to rewrite the `FilterExpressionParser` class so that it's better designed and maintains parity with the functionality of the existing version - this will involve better parsing of the OData filter query.

Once I've done that, I'll then look at supporting Precedence Grouping.

**Comment by roly445** [comment]
Ok sounds great. I don't know if you have seen it but there is a project called LinqToQuerystring, https://github.com/roysvork/linqtoquerystring, that does a similar type of parsing might be worth a look.

**Comment by TrevorPilley** [comment]
I hadn't, although from a brief look it's built to work against an `IQueryable`, the reason I built mine is for when your data source is not exposed via `IQueryable` so I don't think it'll be any use in this case

**Comment by roly445** [comment]
Yep, It's an IQueryable, but I kind of meant about the query string parsing.

**Comment by TrevorPilley** [comment]
Requires #37

**Comment by TrevorPilley** [comment]
@roly445 I've got the re-write of the internals done so I'll start looking at the grouping stuff next. Once that's done I'll need to update MicroLite.Extensions.WebApi to utilise the updated OData library

**Comment by roly445** [comment]
Fantastic, I'm looking forward to seeing it.

**Comment by TrevorPilley** [comment]
@roly445 - I've pushed a beta of both this library and MicroLite.Extensions.WebApi to NuGet. Can you try them out and see if they work as you expected?

**Comment by roly445** [comment]
Getting there, but not quite. I just created the following query, ````?$filter=(((FirstName eq 'andrew') and (LastName eq 'davis')) or (FirstName eq 'system'))&```` and it generated the following paged sql query
````exec sp_executesql N'SELECT COUNT(*) FROM [User] WHERE (((FirstName = @p0) AND ((LastName = @p1) OR (FirstName = @p2))));
SELECT [EmailAddress],[FirstName],[Id],[IsConfirmed],[LastName] FROM (SELECT [EmailAddress],[FirstName],[Id],[IsConfirmed],[LastName],ROW_NUMBER() OVER(ORDER BY (SELECT NULL)) AS RowNumber FROM [User] WHERE (((FirstName = @p3) AND ((LastName = @p4) OR (FirstName = @p5))))) AS [User] WHERE (RowNumber >= @p6 AND RowNumber <= @p7)',N'@p0 nvarchar(6),@p1 nvarchar(5),@p2 nvarchar(6),@p3 nvarchar(6),@p4 nvarchar(5),@p5 nvarchar(6),@p6 int,@p7 int',@p0=N'andrew',@p1=N'davis',@p2=N'system',@p3=N'andrew',@p4=N'davis',@p5=N'system',@p6=1,@p7=100````
The grouping is there, but it's around the wrong items

**Comment by TrevorPilley** [comment]
Just out of interest, does it work correctly without the outer parenthesis? I don't think I tried anything with that..

**Comment by roly445** [comment]
Yep, that works fine.

**Comment by TrevorPilley** [comment]
OK cool, I'm just updating the parsing logic to cater for the outer parenthesis - I'll let you know when a new beta is pushed.

**Comment by TrevorPilley** [comment]
@roly445 - There's a new beta of each package if you want to try it out?

**Comment by roly445** [comment]
Works great!

**Comment by TrevorPilley** [comment]
Excellent! I'll get that published as a release binary in the next day or two
