### ISSUE TITLE
Odata version 4

### ISSUE THREAD

**Issue by anthony-redFox** [TrevorPilley/Net.Http.WebApi.OData#42]
Do you have plans add support Odata version 4 spec?
From - [version 3](http://www.odata.org/documentation/odata-version-3-0)
Note: OData Version 4.0 is the current recommended version of OData. **OData Version 4.0 has been standardized by OASIS** and has many features not included in OData Version 3.0.

[Odata version 4 spec](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html)

**Comment by TrevorPilley** [comment]
Yes, there are parts of the query syntax I would like to implement, there are a couple of bits in v3 which I haven't yet implemented either.

Is there something in v4 which is preventing you from using this library or are you just wanting to use some of the new data types and methods?

**Comment by anthony-redFox** [comment]
For example: In v3 -  "substringof" function is the same "contains" in v4. But v4 doesn't support "substringof".

**Comment by TrevorPilley** [comment]
Closing this now as work has started on OData 4 support - check the [milestone](https://github.com/TrevorPilley/Net.Http.WebApi.OData/milestones/4.0.0) and [branch](https://github.com/TrevorPilley/Net.Http.WebApi.OData/tree/odata-v4) for further info.
