### ISSUE TITLE
.netcore 1.0 or 1.1 support ?

### ISSUE THREAD

**Issue by Ocean-Data** [TrevorPilley/Net.Http.WebApi.OData#92]
hi, do you have plan to supports .netcore?

xiaoxin

**Comment by TrevorPilley** [comment]
Hi, it's something I'm going to look into after I've finished the OData 4.0 support.

**Comment by TrevorPilley** [comment]
Since Microsoft.AspNet.WebApi.Client supports .NETStandard2.0, it should be possible to add a NETSTD20 build
