### ISSUE TITLE
$filter query with white space

### ISSUE THREAD

**Issue by vinaysharma77** [TrevorPilley/Net.Http.WebApi.OData#93]
Hello,

I'm trying to use Net.Http.WebApi.OData to parse the incoming odata query and supply it to our in-house traditional Apis for performing search. The challenge I'm running into is the fields defined in our system has white space and those fields needs to get supplied in the $filter query:

"$filter=First Name eq 'John' and Last Name eq 'Smith'

I tried to encode it to %20 but that didn't work:

"$filter=First%20Name eq 'John' and Last%20Name eq 'Smith'

Is there some other encoding for white space that Net.Http.WebApi.OData uses to parse the incoming query? How do you propose to handle this?

Thanks,
Vin

**Comment by TrevorPilley** [comment]
Hi, property names can't contain a space, if you control the client API you could do something like using an underscore in the API and replacing that before you query the underlying data source?

Also, if you are implementing your own parsing logic, you may find it useful to extend this base class: Net.Http.WebApi.OData/Query/Binders/AbstractFilterBinder if you aren't already.

**Comment by vinaysharma77** [comment]
Thanks for your quick response. I actually wrote my own ModelBinder which follows pretty much the same pattern as the AbstractFilterBinder. The only challenge is with the space between field names.. The problem with using an underscore is, it could be part of the actual field name. I'll have to figure out a different character..

**Comment by TrevorPilley** [comment]
The pattern for property names is upper and lower case alpha plus numeric and underscore - that's your lot, you could use a double underscore if you might have a legitimate single underscore separator in a field name?

**Comment by vinaysharma77** [comment]
Yes.. but even if I come up with any character to define space in the field name, that would too be specific to my implementation and I don't want to deviate from the industry standards of OData. Hence I've decided to write a string extension method which would remove all the white spaces from the field name in the schema definition supplied to the client. So the client will not supply spaces in the field names. And when the odata search request comes in, I'll use the same method to covert the internal field names to remove the spaces and then compare them with the incoming field names in the odata query. I think this should work and let me stay with the OData industry standards.
